### ISSUE TITLE
Syntax error: word unexpected (expecting ")")

### ISSUE THREAD

**Issue by atd** [imagemin/imagemin-pngcrush#2]
After a fresh install, I get the following error:

```
Error: Command failed: /home/atd/dev/pear2pear/node_modules/imagemin-pngcrush/node_modules/pngcrush-bin/vendor/pngcrush: 1: /home/atd/dev/pear2pear/node_modules/imagemin-pngcrush/node_modules/pngcrush-bin/vendor/pngcrush: Syntax error: word unexpected (expecting ")")

    at ChildProcess.exithandler (child_process.js:658:15)
    at ChildProcess.emit (events.js:98:17)
    at maybeClose (child_process.js:766:16)
    at Socket.<anonymous> (child_process.js:979:11)
    at Socket.emit (events.js:95:17)
    at Pipe.close (net.js:466:12)
```

**Comment by kevva** [comment]
What OS?

**Comment by atd** [comment]
Debian testing.

The arch is i386 and pngcrush binary is `ELF 64-bit LSB executable, x86-64` so maybe the problem resides there?

**Comment by sindresorhus** [comment]
Closing as no one else has encountered this and it's very old.
